services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  minio:
    image: 'minio/minio:latest'
    command: server /data --console-address ":9001"
    environment:
      - 'MINIO_ROOT_USER=minio'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  solr:
    image: 'solr:latest'
    ports:
      - '8983:8983'

volumes:
  minio_data: