spring.application.name=dating-recommendations-user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# go recommendation service
recommendation.service.url=${RECOMMENDATION_SERVICE_URL}
recommendation.service.enabled=false

# use local recommender with solr search
recommender.solr.url=http://localhost:8983/solr/mycollection
recommender.solr.base-url=http://localhost:8983/solr
recommender.solr.collection=mycollection
recommender.solr.enabled=true
recommender.solr.data-seed-enabled=true

minio.url=http://localhost:9000
minio.access-key=minio
minio.secret-key=minioadmin
minio.bucket-name=profile-pictures

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/oauth/jwks.json