spring.application.name=dating-recommendations-user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# recommendation service
recommendation.service.url=${RECOMMENDATION_SERVICE_URL}

# supabase connection
supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET}